name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: cache pkgs
        id: cache-apt
        uses: actions/cache@v6
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-sdl2-v1
      - name: install sdl2
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
